name: Feature Request
description: Suggest a new feature
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: ETC
    attributes:
      label: ETC
    validations:
      required: false
